-- MySQL Script generated by MySQL Workbench
-- 05/11/15 17:23:50
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blizzard_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `blizzard_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `blizzard_db` ;

-- -----------------------------------------------------
-- Table `blizzard_db`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blizzard_db`.`event` ;

CREATE TABLE IF NOT EXISTS `blizzard_db`.`event` (
  `event_id` INT NOT NULL AUTO_INCREMENT,
  `event_name` VARCHAR(35) NULL,
  `event_description` TEXT(1000) NULL,
  `event_date` DATETIME NOT NULL,
  `event_image` MEDIUMBLOB NULL,
  `event_validated` TINYINT(1) NULL,
  `event_shifts_link` TEXT(2000) NULL,
  `event_location_name` VARCHAR(45) NULL,
  `event_location_address` VARCHAR(45) NULL,
  `event_location_coordinates` VARCHAR(45) NULL,
  PRIMARY KEY (`event_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blizzard_db`.`form`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blizzard_db`.`form` ;

CREATE TABLE IF NOT EXISTS `blizzard_db`.`form` (
  `form_id` INT NOT NULL AUTO_INCREMENT,
  `form_name` VARCHAR(45) NULL,
  `fk_event_id` INT NOT NULL,
  PRIMARY KEY (`form_id`),
  INDEX `fk_form_event_idx` (`fk_event_id` ASC),
  CONSTRAINT `fk_form_event`
    FOREIGN KEY (`fk_event_id`)
    REFERENCES `blizzard_db`.`event` (`event_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blizzard_db`.`field_type`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blizzard_db`.`field_type` ;

CREATE TABLE IF NOT EXISTS `blizzard_db`.`field_type` (
  `field_type_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`field_type_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blizzard_db`.`input_field`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blizzard_db`.`input_field` ;

CREATE TABLE IF NOT EXISTS `blizzard_db`.`input_field` (
  `input_field_id` INT NOT NULL AUTO_INCREMENT,
  `input_field_name` VARCHAR(25) NOT NULL,
  `input_field_comment` TEXT(100) NULL,
  `input_field_position` INT NOT NULL,
  `fk_field_type_name` VARCHAR(15) NOT NULL,
  `fk_form_id` INT NOT NULL,
  PRIMARY KEY (`input_field_id`),
  INDEX `fk_input_field_field_type_idx` (`fk_field_type_name` ASC),
  INDEX `fk_input_field_form_idx` (`fk_form_id` ASC),
  CONSTRAINT `fk_input_field_field_type`
    FOREIGN KEY (`fk_field_type_name`)
    REFERENCES `blizzard_db`.`field_type` (`field_type_name`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_input_field_form`
    FOREIGN KEY (`fk_form_id`)
    REFERENCES `blizzard_db`.`form` (`form_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blizzard_db`.`subscriber`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blizzard_db`.`subscriber` ;

CREATE TABLE IF NOT EXISTS `blizzard_db`.`subscriber` (
  `subscriber_id` INT NOT NULL AUTO_INCREMENT,
  `fk_form_id` INT NULL,
  PRIMARY KEY (`subscriber_id`),
  INDEX `fk_form_subscriber_idx` (`fk_form_id` ASC),
  CONSTRAINT `fk_form_subscriber`
    FOREIGN KEY (`fk_form_id`)
    REFERENCES `blizzard_db`.`form` (`form_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blizzard_db`.`data`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blizzard_db`.`data` ;

CREATE TABLE IF NOT EXISTS `blizzard_db`.`data` (
  `data_id` INT NOT NULL AUTO_INCREMENT,
  `fk_input_field_id` INT NOT NULL,
  `data_value` VARCHAR(100) NULL,
  `fk_subscriber_id` INT NOT NULL,
  PRIMARY KEY (`data_id`),
  INDEX `fk_input_field_data_idx` (`fk_input_field_id` ASC),
  INDEX `fk_subscriber_data_idx` (`fk_subscriber_id` ASC),
  CONSTRAINT `fk_input_field_data`
    FOREIGN KEY (`fk_input_field_id`)
    REFERENCES `blizzard_db`.`input_field` (`input_field_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscriber_data`
    FOREIGN KEY (`fk_subscriber_id`)
    REFERENCES `blizzard_db`.`subscriber` (`subscriber_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
